spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

app:
  security:
    csrf:
      enabled: false   # K6·Postman 테스트 무마찰을 위해 비활성

logging:
  level:
    com.solvemeup: debug
    org.hibernate.SQL: debug
