spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.solvemeup: debug
    org.hibernate.SQL: debug

app:
  security:
    csrf:
      enabled: false   # K6·Postman 테스트 무마찰을 위해 비활성
