spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    com.solvemeup: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
